name: app_c20785
description: App source code for 20785C

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/20785C-logo.png
    - assets/logo-inverted-colour.png
    - assets/logo-transparent.png
  fonts:
    - family: Roboto Mono
      fonts:
        - asset: assets/RobotoMono-Regular.ttf
