name: app_c20785
description: App source code for 20785C

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  # App state
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  # Launcher configuration
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.11.0
  # HTTP
  http: ^1.1.0

flutter_icons:
  image_path: "assets/logo-transparent.png"
  android: true
  ios: true

flutter_app_name:
  name: "20785C App"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/20785C-logo.png
    - assets/logo-inverted-colour.png
    - assets/logo-transparent.png
  fonts:
    - family: Roboto Mono
      fonts:
        - asset: assets/RobotoMono-Regular.ttf
